server:
  port: 8091
Spring:
  datasource:
    driver-class-name: com.myslq.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sb_c_2021?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: geotjeoli
    password: gjl123414
mybatis:
  type-aliases-package: com.jtj.exam.demo.vo  